### ISSUE TITLE
Refactor render loop

### ISSUE THREAD

**Issue by tzachshabtay** [tzachshabtay/MonoAGS#207]
Instead of render loop having a direct dependency on IObject, introduce an IRenderer interface and a subscription mechanism in the renderer loop. Components will be able to subscribe and provide custom rendering logic.

**Comment by tzachshabtay** [comment]
While investigating a "jittering" issue in the "Last & Furious" game I got to the conclusion that the core of the problem is that the update thread and the render thread are not synchronized. The update thread can be in the middle of updating state while the rendering thread is rendering it. 
Usually this would be fine as the rendering thread will then render the correct state on the next frame, and the human eye would not notice at 60 FPS, but in the case (like in "Last & Furious") where the state changes rapidly on each frame this mis-synchronization can continue on several frames causing the jitter.

And while I have a prototype fix that seems to fix the jitter for that game while using the current architecture (in this branch: https://github.com/tzachshabtay/MonoAGS/tree/FixJittering), I suspect it's not going to work for all scenarios as it doesn't solve the core issue.

For solving the core issue, there needs to be a separation between the update and render thread, so that the render thread gets instructions from the update thread which are immutable -> i.e they won't be touched by the update thread, at least until the render thread is done with it.

So this affects the design for this issue, as the proposed solution will need to be extended. The general idea still applies, the renderer loop (or pipeline) will still have a subscription mechanism, and we'll still introduce `IRenderer` as a new interface. 
The proposed addition would be that instead of `IRenderer` doing the rendering itself, it will supply an `IRenderInstruction` which will do the rendering. That instruction will be supplied by the renderer every time the update loop completes, and the rendering pipeline will use that instruction.

So, as a first iteration, the APIs would look like this:

```csharp

IRenderPipeline
{
   void Subscribe(string entityID, IRenderer renderer);
   void Unsubscribe(string entityID);
}

IRenderInstruction
{
    void Render();
}

IRenderer
{
    IRenderInstruction GetNextInstruction(IViewport viewport);
}

```

The main problem I see with this, is that this will cause a lot of heap allocations every time we create a new instruction. We want to be able to recycle the instructions, so the pipeline needs to be able to release the instruction after it's done with it so that we can reuse it.
So I will add a `Release` method to the `IRenderInstruction` interface to allow that.

Then, the pipeline implementation, in its most simplistic, will look something like this:

```csharp

foreach (var instruction in instructions)
{
       instruction.Render();
       instruction.Release();
}

```

And a simple implementation of the current image renderer (minus the border and pivot cross which will go to different renderers) will look something like this:

```csharp

ImageRendererInstruction : IRenderInstruction
{
    //members
    texture, color, boundingBox, textureBox;
    readonly textureRenderer;

    private GLImageRendererInstruction(textureRenderer)
    {
	this.textureRenderer = textureRenderer;
    }

    public static ObjectPool<GLImageRendererInstruction> InitPool(textureRenderer)
    {
	var factory = _ => new GLImageRendererInstruction(textureRenderer);
        return new ObjectPool<GLImageRenderer>(factory);
    }

    public static IRenderInstruction Create(objectPool, texture, color, boundingBox, textureBox)
    {
	var instruction = objectPool.Acquire();
	instruction.texture = texture;
	instruction.color = color;
	instruction.boundingBox = boundingBox;
	instruction.textureBox = textureBox;
	return instruction;
    }

    public void Render()
    {
	this.textureRenderer.Render(texture, renderBox, color, textureBox);
    }

    public void Release() => _pool.Release(this);
}

ImageRendererComponent : AGSComponent, IRenderer
{
    public override void Init(entity)
    {
	base.Init(entity);
	...
	_pool = ImageRendererInstruction.InitPool(_textureRenderer);
	_renderPipeline.Subscribe(entity.ID, this);
    }

    public override void Dispose()
    {
	_renderPipeline.Unsubscribe(_entity.ID);
    }

    public IRenderInstruction GetNextInstruction(IViewport viewport)
    {
	var boxes = _boundingBoxComponent.GetBoundingBoxes(viewport);
	var texture = getTexture();
	var color = getColor();
	return ImageRendererInstruction.Create(_pool, texture, color, boxes.RenderBox, boxes.TextureBox);
    }

    ...
}

```

(One potential improvement to that implementation would be to avoid creating a new instruction at all if nothing changed from the previous instruction).

One big downside I see with this approach is that it's a noticeable amount of boilerplate code that will need to be written for every renderer, but I don't currently see a way to improve that.

Thoughts?

**Comment by ivan-mogilko** [comment]
So, this reminds me of my very initial proposal where "rendering component" is separated from the "data component" and only takes data from it. If that existed, then render component in whole could itself become an immutable thing for the rendering time.

Maybe something like that could be implemented in the new way?

Also, I am usually more in favor of opposite direction of control: the "view" component taking from "data" component instead of latter pushing its contents into "view".

What if this "rendering instruction" was a constant object created by rendering component, to which it would pass itself as properties supplier? In such case the "instruction" would be notified of a rendering pass start, at which it would gather necessary values from its "parent" in a thread-safe way (locking, etc), then release it and draw what it gathered, then repeat?

**Comment by ivan-mogilko** [comment]
UPD: hmm, I actually realized that in any room that has hidden objects, or simply too large for all objects to be seen at once, then number of renderings will be less than number of objects.

**Comment by tzachshabtay** [comment]
The problem with that approach is that one constant view object is not enough. The view needs to be "locked in" at the end of the update cycle on the update thread, and is used in the render thread.

If you only have one view object, then the update thread might update the view of the car entity in the middle of the render cycle, after the race background was already rendered for the previous update, showing a wrong rendering snapshot. If this happens for several ticks in a row, your eye will notice that "jitter".

With my suggestion, at the end of the update loop, each renderer prepares the instruction to form an immutable instruction set for that update loop, which is then guaranteed to be an accurate snapshot.

**Comment by ivan-mogilko** [comment]
No, in my proposal update thread cannot update the view, it simply does not touch it. It's the view that decides when to update itself from the data.

It looks like this: the "data" part is freely updated by the update thread.
The "view" part is only notified by render thread that it needs to prepare to be rendered. Then it calls "lock" on data part, gathers properties, "unlocks" data part. So the "view" remains immutable since then, and renders only what it managed to gather during preparation phase.

**Comment by ivan-mogilko** [comment]
Hmm, on other hand, unless whole update thread is told to pause while gathering these properties, then there is a theoretical chance that update thread may run again during gathering of data.

**Comment by tzachshabtay** [comment]
Even if the update thread is completely paused, that still won't be enough though: it needs to be completely paused between cycles (because if you pause it mid-cycle, you have the same problem I depicted earlier), and the render thread can't do it, the update thread must be the initiator.

**Comment by tzachshabtay** [comment]
So are you ok then with the initial proposal? Or do you still have an alternative in mind?

**Comment by ivan-mogilko** [comment]
> Even if the update thread is completely paused, that still won't be enough though: it needs to be completely paused between cycles (because if you pause it mid-cycle, you have the same problem I depicted earlier), and the render thread can't do it, the update thread must be the initiator.

Well, this is what I also said in the comment above.

Don't you think this alters original plan? Because in your initial concept it was render loop that lets renderer know when to create instructions. Now, apparently it is update loops that has to do that.

**Comment by ivan-mogilko** [comment]
Erm, no, scratch that.
I think you originally meant that it is update loop that tells renderer component to create instructions?
It's just that it is not clear how IRenderPipeline uses subscriptions?

**Comment by tzachshabtay** [comment]
What I had in mind is that the render pipeline will call GetNextInstruction from the update thread (at the end of the update loop) on all subscribers and will create an instruction set. The render loop, at the start of each tick, will get the instruction set from the pipeline.

**Comment by ivan-mogilko** [comment]
Does this implementation assume that render may lag whole loop behind? I mean, update loop prepares drawing instructions, but while render is working update finishes again. What will happen then?

**Comment by tzachshabtay** [comment]
I see two possible interpretations of your question, so I'll answer both.
1. In the case the render loop is in the middle of an update it wouldn't matter to the update loop as the instructions prepared by the update loop will be in a separate object, so they can work in parallel.
2. If you're worried about whether we should delay the updates if the rendering is delayed, then I think no. I assumed that in this case the render loop will simply skip an instruction set, so the pace will be consistent and the user will not feel a slow down. For example, we may even configure the update loop to be in 120 FPS and the render loop to be in 30 FPS so the render loop will render once every 4 updates, but will render the last update.

**Comment by ivan-mogilko** [comment]
What I meant is, are you going to consider hypothetical situation when next update happens when previous rendering is still not completed (either rendering is too slow, or update is too fast)?
In that case the next update iteration will arrive at the point when it needs to prepare drawing instructions, while rendering is still going. Update cannot fill instructions again, because if it does it will supply new iteration of instructions to the previous iteration of render loop.

**Comment by ivan-mogilko** [comment]
Wait, I probably misunderstood again. When you say "instructions will be in a separate object", do you mean that there will be separate "pipeline" objects per each update iteration?

**Comment by ivan-mogilko** [comment]
Sorry, I will try to elaborate again just in case.
The situation I was trying to describe is this:
* the update loop prepares drawing instructions after iteration A.
* render loop starts new iteration using instructions A.
* for some hypothetical reasons update loop finishes iteration B while render loop still rendering instructions from A.
* so now the question is, should the update loop begin filling in new set of drawing instructions for B, and if yes, then where it saves them? because if it tries to push them into same list of instructions, rendering will be "broken" again. (or will it?)

**Comment by tzachshabtay** [comment]
Yes, the update loop should begin filling in new set of instructions for B, and that array of instructions is saved in a different object (and we can use an object pool for the array the same way we use a pool for the individual instructions).
