### ISSUE TITLE
Audio- support reducing volume for playing sounds when speech is playing

### ISSUE THREAD

**Issue by tzachshabtay** [tzachshabtay/MonoAGS#73]

**Comment by ivan-mogilko** [comment]
Question: is audio caregories (division on music/effects etc) supported by the engine, or planned to be?
I was about to suggest it, if it is not yet implemented.
(Actually, I was about to propose a more sophisticated audio management built as an additional layer over sound clips, but that may be not the place to post it)

Since new audio system was introduced in AGS, "volume reduction when speech is played" is a property of audio category, which you may freely set for any audio type, including custom ones.

It might even have sense to go further and make a cross-reference table of reactions of audio types on different audio types (e.g. reduce music volume when "important sound" category is playing, and so forth).

**Comment by tzachshabtay** [comment]
Currently there are no categories for audio clips in the engine.
What I had in mind for this (and this is the correct place, as I wanted to add it for this feature), instead of categories, is the ability to tag audio clips. So unlike categories, an audio clip might have multiple tags attached to it, so a specific audio clip might have a "speech" tag, but also a "in a cave" tag.

And then you'll be able to build rules on top of the tag system, where the "volume reduction when speech is played" is going to be, for now, the only built in rule.
